workspace:
    build: docker/workspace/
    volumes:
        - .:/var/www/html/
elasticsearch:
    build: docker/elasticsearch/
    ports:
        - 9200:9200
mongodb:
    image: mongo:3
    ports:
        - 27017:27017
mysql:
    build: docker/mysql/
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: application
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
        - 3306:3306
redis:
    image: redis:3
    ports:
        - 6379:6379
selenium_hub:
    image: selenium/hub:3.0.1
    ports:
        - 4444
selenium_node_firefox:
    build: docker/selenium-firefox
    links:
        - selenium_hub
    environment:
        - HUB_PORT_4444_TCP_ADDR=selenium_hub
    expose:
        - 5555
php:
    build: docker/php/
    environment:
        - BLACKFIRE_SERVER_ID=X
        - BLACKFIRE_SERVER_TOKEN=X
        - GITHUB_OAUTH_TOKEN=X
    volumes:
        - ~/.gitconfig:/var/www/.gitconfig
        - ~/.gitignore_global:/var/www/.gitignore_global
        - ~/.ssh:/var/www/.ssh
    volumes_from:
        - workspace
    links:
        - elasticsearch
        - mongodb
        - mysql
        - redis
        - selenium_hub
    ports:
        - 80:80
    dns:
        - 8.8.8.8
        - 8.8.4.4